name: publish-to-npm
on:
  pull_request:
    branches:
      - "main" # Change this if not your default branch
    paths:
      - "package.json"
jobs:
  publish:
    if: github.repository == 'adobe/plugin-on-fetch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          access: "public"
